//
// Created by wmurphy on 9/10/2019.
//

#ifndef DATASTRCTURES_ALGORITHMS_INDEXOUTOFBOUNDSEXCEPTION_H
#define DATASTRCTURES_ALGORITHMS_INDEXOUTOFBOUNDSEXCEPTION_H


class IndexOutOfBoundsException {

};


#endif //DATASTRCTURES_ALGORITHMS_INDEXOUTOFBOUNDSEXCEPTION_H
